stages:
  - test
  - stats
  - release

stylecheck:
  stage: test
  tags:
    - python3
    - ruby
    - gem
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - ruby-rubocop

build_gem:
  stage: test
  tags:
    - ruby
    - gem
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - ruby-gem-build
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/*

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
    - progstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gitstats-gen

docgen:
  stage: stats
  tags:
    - python3
    - progstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - rdoc-docgen

release_upload:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

publish_gem:
  stage: release
  only:
    - master
  tags:
    - gem
    - ruby
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - ruby-gem-publish
