stages:
  - mirror
  - build
  - publish

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/blackjack.git master -f

build_gem:
  stage: build
  tags:
    - gem
    - ruby
  script:
    - gem build blackjack.gemspec
  artifacts:
    paths:
      - ./*.gem

publish_gem:
  stage: publish
  only:
    - master
  tags:
    - gem
    - ruby
  script:
    - mkdir -p ~/.gem/
    - echo $RUBYGEMS_CREDENTIALS > ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - gem push ./*.gem
    - rm ~/.gem/credentials

upload_release_to_github:
  stage: publish
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/github-release-uploader.git
    - git clone https://gitlab.namibsun.net/namboy94/changelog-reader.git
    - python changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python github-release-uploader/github-release-uploader.py namboy94 blackjack $GITHUB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: publish
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/gitlab-release-uploader.git
    - git clone https://gitlab.namibsun.net/namboy94/changelog-reader.git
    - python changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python gitlab-release-uploader/gitlab-release-uploader.py namboy94 blackjack $GITLAB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master -u https://gitlab.namibsun.net
