stages:
    - mirror
    - build
    - deploy

mirror_repo:
    stage: mirror
    only:
        - master
    script:
        - git push -u git@github.com:namboy94/ruby-blackjack.git master

build_gem:
    stage: build
    only:
        - master
    script:
        gem build ruby-blackjack.gemspec
    artifacts:
        paths:
            - ./*.gem

deploy_gem:
    stage: deploy
    only:
        - master
    script:
        - gem build ruby-blackjack.gemspec
        - gem push ./*.gem